* snek
Static deployment: https://effortless-youtiao-c31d3d.netlify.app
** TODO
*** Backend
**** Integrate backend and persist high scores.
**** User authorization
**** Fake monetization system!!! Users have to "purchase" credits.
*** Frontend
**** Abstract out class of "apple".
Apple class should have score and "bonus" attributes, something like this.
** KNOWN BUGS
***  Apple generation needs to not collide with snek
Solution: I would like to come up with something that is a little better than O(N*M) but number of cells is really only 40x30 so strictly speaking it would be totally fine to take a low-brow approach, at least for the time being.
***  Key latency allows reveral of direction, unexpected collisions. Try hitting down/left etc simultaneously.
Solution: Should be simple, we either need to buffer input or disregard events outside of frame interval. The former is probably the best option.
** DISCOVERIES
*** Input elements can be hardcoded to width of characters defined by font-size.
One need only supply width: attribute in terms of "ch" i.e. width: 3ch --> coupled with a maxlength of 3 defined in html, this forced hard convention.
